[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
padding.x = 10
padding.y = 0
startup_mode = "Maximized"

[font]
normal.family = "FiraCode Nerd Font"
size = 18

# Colors (Gruvbox Material Medium)

[colors.primary]
background = '#292828'
foreground = '#d4be98'

[colors.normal]
black = '#32302f'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'

[colors.bright]
black = '#7c6f64'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#d4be98'
